[project]
protostar-version = "0.8.1"
lib-path = "lib"
cairo-path = ["./lib/cairo_contracts/src"]

[contracts]
FactoryProxy = ["contracts/FactoryProxy.cairo"]
Factory = ["contracts/Factory.cairo"]
RouterProxy = ["contracts/RouterProxy.cairo"]
Router = ["contracts/Router.cairo"]
PairProxy = ["contracts/PairProxy.cairo"]
Pair = ["contracts/Pair.cairo"]
Multicall = ["contracts/utils/Multicall.cairo"]

